apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-ing
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  uptimekuma
            port:
              number: 3001

---
#T* Service
apiVersion: v1
kind: Service
metadata:
  name: uptimekuma
  labels:
    app: uptimekuma 

spec:
  selector:
    app: uptimekuma
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

--- 
#T* StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptimekuma
  labels:
    app: uptimekuma

spec:
  serviceName: "uptimekuma"
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  
  template:
    metadata:
      generateName: uptimekuma
      labels:
        app: uptimekuma
  
    spec:

      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma
          imagePullPolicy: IfNotPresent
          resources: {}
        
          ports:
            - containerPort: 3001

          volumeMounts:
            - name: data 
              mountPath: /app/data
      
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

status: 
  replicas: 1